name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.5"
      - run: go test ./...
